# Generated by Django 6.1 on 2026-08-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('chamber_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chamber_code', models.CharField(max_length=20, unique=True)),
                ('chamber_type', models.CharField(default='SETTING', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('chamber_id',),
            },
        ),
        migrations.CreateModel(
            name='Glaze',
            fields=[
                ('glaze_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('glaze_code', models.CharField(max_length=20, unique=True)),
                ('glaze_name', models.CharField(max_length=100)),
                ('formula', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_combined', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('glaze_id',),
            },
        ),
        migrations.CreateModel(
            name='KilnSensor',
            fields=[
                ('sensor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sensor_code', models.CharField(max_length=30, unique=True)),
                ('sensor_name', models.CharField(blank=True, default='', max_length=50)),
                ('position_order', models.SmallIntegerField(default=0)),
                ('is_measured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position_order', 'sensor_id'),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operator_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('operator_id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code_kiln', models.CharField(blank=True, default='', max_length=20)),
                ('product_code_packing', models.CharField(blank=True, default='', max_length=20)),
                ('product_name_setting', models.CharField(blank=True, default='', max_length=100)),
                ('product_group', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('product_id',),
            },
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('wagon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wagon_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ('wagon_id',),
            },
        ),
        migrations.CreateModel(
            name='PackingHeader',
            fields=[
                ('packing_header_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pack_date', models.CharField(blank=True, default='', max_length=10)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
                ('worker_count', models.IntegerField(blank=True, null=True)),
                ('client_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(blank=True, db_column='controller_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.operator')),
            ],
            options={
                'ordering': ('packing_header_id',),
            },
        ),
        migrations.CreateModel(
            name='WagonTrip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('body_dried', 'body_dried'), ('in_progress', 'in_progress'), ('waiting_hall', 'waiting_hall'), ('in_tunnel', 'in_tunnel'), ('awaiting_discharge', 'awaiting_discharge'), ('completed', 'completed'), ('abandoned', 'abandoned'), ('incomplete', 'incomplete')], default='in_progress', max_length=20)),
                ('source_module', models.CharField(default='setting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wagon', models.ForeignKey(db_column='wagon_id', on_delete=django.db.models.deletion.PROTECT, to='mes.wagon')),
            ],
            options={
                'ordering': ('trip_id',),
            },
        ),
        migrations.CreateModel(
            name='SettingLoad',
            fields=[
                ('setting_load_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
                ('date_jalali', models.CharField(blank=True, default='', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('packages', models.IntegerField(blank=True, null=True)),
                ('khesht_count', models.IntegerField(blank=True, null=True)),
                ('client_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber', models.ForeignKey(blank=True, db_column='chamber_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.chamber')),
                ('glaze', models.ForeignKey(blank=True, db_column='glaze_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.glaze')),
                ('operator', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.operator')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.product')),
                ('wagon', models.ForeignKey(db_column='wagon_id', on_delete=django.db.models.deletion.PROTECT, to='mes.wagon')),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.PROTECT, related_name='setting_loads', to='mes.wagontrip')),
            ],
            options={
                'ordering': ('setting_load_id',),
            },
        ),
        migrations.CreateModel(
            name='PackingWagon',
            fields=[
                ('packing_wagon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('grade1_count', models.IntegerField(blank=True, null=True)),
                ('grade2_count', models.IntegerField(blank=True, null=True)),
                ('waste_count', models.IntegerField(blank=True, null=True)),
                ('packing_header', models.ForeignKey(db_column='packing_header_id', on_delete=django.db.models.deletion.CASCADE, related_name='wagons', to='mes.packingheader')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.product')),
                ('wagon', models.ForeignKey(db_column='wagon_id', on_delete=django.db.models.deletion.PROTECT, to='mes.wagon')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_wagons', to='mes.wagontrip')),
            ],
            options={
                'ordering': ('packing_wagon_id',),
            },
        ),
        migrations.CreateModel(
            name='KilnPush',
            fields=[
                ('kiln_push_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('push_seq', models.BigIntegerField(unique=True)),
                ('push_date', models.CharField(blank=True, default='', max_length=10)),
                ('push_time', models.TimeField(blank=True, null=True)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
                ('push_duration', models.DurationField(blank=True, null=True)),
                ('client_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.operator')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.product')),
                ('wagon', models.ForeignKey(db_column='wagon_id', on_delete=django.db.models.deletion.PROTECT, to='mes.wagon')),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.PROTECT, related_name='kiln_pushes', to='mes.wagontrip')),
            ],
            options={
                'ordering': ('push_seq',),
            },
        ),
        migrations.CreateModel(
            name='KilnReading',
            fields=[
                ('kiln_reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kiln_push', models.ForeignKey(db_column='kiln_push_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='mes.kilnpush')),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.PROTECT, to='mes.kilnsensor')),
            ],
            options={
                'unique_together': {('kiln_push', 'sensor')},
            },
        ),
        migrations.CreateModel(
            name='KilnExit',
            fields=[
                ('kiln_exit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_push_seq', models.IntegerField(blank=True, null=True)),
                ('exit_push_seq', models.IntegerField(blank=True, null=True)),
                ('exit_date', models.CharField(blank=True, default='', max_length=10)),
                ('discharged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wagon', models.ForeignKey(db_column='wagon_id', on_delete=django.db.models.deletion.PROTECT, to='mes.wagon')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kiln_exits', to='mes.wagontrip')),
            ],
            options={
                'ordering': ('exit_push_seq',),
                'unique_together': {('wagon', 'exit_push_seq')},
            },
        ),
    ]
