# Generated by Django 6.1 on 2026-08-29 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingEvent',
            fields=[
                ('setting_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_jalali', models.CharField(blank=True, default='', max_length=10)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
                ('personnel_count', models.IntegerField(blank=True, null=True)),
                ('fingers_count', models.IntegerField(blank=True, null=True)),
                ('columns_count', models.IntegerField(blank=True, null=True)),
                ('dryer_waste', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber', models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.PROTECT, to='mes.chamber')),
                ('operator', models.ForeignKey(blank=True, db_column='operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setting_operator', to='mes.operator')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.product')),
                ('supervisor', models.ForeignKey(blank=True, db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_setting_events', to='mes.operator')),
            ],
            options={
                'ordering': ('setting_event_id',),
            },
        ),
        migrations.CreateModel(
            name='SettingWagon',
            fields=[
                ('setting_wagon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('packages', models.IntegerField(blank=True, null=True)),
                ('khesht_count', models.IntegerField(blank=True, null=True)),
                ('position_in_event', models.SmallIntegerField(default=1)),
                ('glaze', models.ForeignKey(blank=True, db_column='glaze_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.glaze')),
                ('setting_event', models.ForeignKey(db_column='setting_event_id', on_delete=django.db.models.deletion.PROTECT, related_name='wagons', to='mes.settingevent')),
                ('trip', models.ForeignKey(blank=True, db_column='trip_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setting_wagons', to='mes.wagontrip')),
                ('wagon', models.ForeignKey(db_column='wagon_id', on_delete=django.db.models.deletion.PROTECT, to='mes.wagon')),
            ],
            options={
                'ordering': ('setting_event', 'position_in_event'),
                'unique_together': {('setting_event', 'wagon', 'position_in_event')},
            },
        ),
        migrations.DeleteModel(
            name='SettingLoad',
        ),
    ]
