# Generated by Django 6.1 on 2026-08-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0002_settingevent_settingwagon_delete_settingload'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingevent',
            name='client_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
