# Generated by Django 6.1 on 2026-08-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0003_settingevent_client_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryerCycle',
            fields=[
                ('dryer_cycle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('load_date', models.CharField(blank=True, default='', max_length=10)),
                ('load_time', models.TimeField(blank=True, null=True)),
                ('unload_date', models.CharField(blank=True, default='', max_length=10)),
                ('unload_time', models.TimeField(blank=True, null=True)),
                ('finger_count', models.IntegerField(blank=True, null=True)),
                ('chamber_no', models.IntegerField(blank=True, null=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamber', models.ForeignKey(blank=True, db_column='chamber_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.chamber')),
                ('load_operator', models.ForeignKey(blank=True, db_column='load_operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mes.operator')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='mes.product')),
                ('unload_operator', models.ForeignKey(blank=True, db_column='unload_operator_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mes.operator')),
            ],
            options={
                'ordering': ('dryer_cycle_id',),
            },
        ),
        migrations.CreateModel(
            name='DryerReading',
            fields=[
                ('dryer_reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour_offset', models.IntegerField(blank=True, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dryer_cycle', models.ForeignKey(db_column='dryer_cycle_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='mes.dryercycle')),
            ],
            options={
                'unique_together': {('dryer_cycle', 'hour_offset')},
            },
        ),
    ]
