# Generated by Django 6.1 on 2026-08-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0004_dryercycle_dryerreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlReject',
            fields=[
                ('etl_reject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('setting', 'setting'), ('kiln', 'kiln'), ('packing', 'packing'), ('dryer', 'dryer')], max_length=20)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('raw', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('etl_reject_id',),
            },
        ),
    ]
