# Generated by Django 6.1 on 2026-08-31 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0005_etlreject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberState',
            fields=[
                ('chamber', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='state', serialize=False, to='mes.chamber')),
                ('is_loaded', models.BooleanField(default=False)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_dryer_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mes.dryercycle')),
                ('current_setting_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mes.settingevent')),
            ],
            options={
                'ordering': ('chamber',),
            },
        ),
    ]
