# Generated by Django 6.1 on 2026-09-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0006_chamberstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagontrip',
            name='chamber_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wagontrip',
            name='entered_waiting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wagontrip',
            name='exited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wagontrip',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wagontrip',
            name='total_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wagontrip',
            name='wagon_plate',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
